# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c236451e20d39116140ee61769a13288643c9df764718ef65bfb8c521ca7a4cf2dccfc170c97f62cef92f04f4b860ff0c4f79324d4241fb9f8227239f3619c42

test:
  secret_key_base: f95bf504d106ea4ad703ffed90b6eaef97b0e47cb0ec5233b1e2fd35a7d8eff578bdf3228d4afc568a6237c0dbdbdafd8d2ed2949534fc096e0d9bed29ff8e57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
